default_language_version:
    python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
      exclude_types:
        - "svg"
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: pretty-format-json
    - id: check-symlinks
    - id: check-toml
    - id: debug-statements
    - id: mixed-line-ending

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black

# Replaced by ruff
# - repo: https://github.com/pycqa/isort
#   rev: 5.12.0
#   hooks:
#     - id: isort
#       language_version: python3

# Too much depends on context (ie. unknown but valid code-words added to config)
# As a consequence, it can produces a lot of false positives since it's added words
# can.t be git committed
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.2.5
#   hooks:
#   - id: codespell
