name: tests

on:
  push:
    branches-ignore:
      # Once thing had been pushed to master branch, tests have already had to run and
      # pass so no need to run them again
      - "master"
      - "main"


jobs:
  run_tests:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    name: "${{ matrix.os }} 🔹 🐍 ${{ matrix.python-version }}"

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: "📦 set up 🐍 ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: "📦 install seveno-pyutil"
        run: uv sync --dev

      - name: "run tests"
        run: uv run pytest .

      #---------------------------------------------------------------------------------
      # Tests coverage
      #---------------------------------------------------------------------------------
      # We need coverage data only from single tests run.
      - name: "run tests with coverage 🔹 🐍 3.13"
        if: ${{ matrix.python-version == '3.13'}}
        run: uv run coverage run -m pytest

      - name: "coverage report 🔹 🐍 3.13"
        if: ${{ matrix.python-version == '3.13'}}
        run: uv run coverage report

      - name: "generate coverage xml 🔹 🐍 3.13"
        if: ${{ matrix.python-version == '3.13'}}
        run: uv run coverage xml -i

      - name: "generate coverage report 🔹 🐍 3.13"
        if: ${{ matrix.python-version == '3.13'}}
        run: uv run coverage report

      - name: "upload coverage to codecov.io 🔹 🐍 3.13"
        if: ${{ matrix.python-version == '3.13'}}
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.xml
